<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Data Analysis</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="plots.html">Food Deserts</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="http://github.com/tl3279/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Data Analysis</h1>

</div>


<pre class="r"><code>knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
## ✔ purrr     1.0.2     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<pre class="r"><code>library(haven)
library(readxl)
library(plotly)</code></pre>
<pre><code>## 
## Attaching package: &#39;plotly&#39;
## 
## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot
## 
## The following object is masked from &#39;package:stats&#39;:
## 
##     filter
## 
## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<pre class="r"><code>library(sf)</code></pre>
<pre><code>## Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE</code></pre>
<pre class="r"><code>library(VGAM)</code></pre>
<pre><code>## Loading required package: stats4
## Loading required package: splines</code></pre>
<p><strong>Data Importing, Cleaning and Selecting</strong></p>
<pre class="r"><code>brfss_22 = read_csv(&quot;NYSDOH_BRFSS_Survey_Data_2022.csv&quot;)|&gt;
  janitor::clean_names()</code></pre>
<pre class="r"><code>zipcode = 
  brfss_22 |&gt;
  filter(zipcode1 != &quot;Data do not meet the criteria for statistical reliability, data quality or confidentiality (data are suppressed)&quot;)

head(zipcode)</code></pre>
<pre><code>## # A tibble: 0 × 343
## # ℹ 343 variables: state &lt;chr&gt;, fmonth &lt;dbl&gt;, idate &lt;chr&gt;, imonth &lt;chr&gt;,
## #   iday &lt;chr&gt;, iyear &lt;dbl&gt;, seqno &lt;dbl&gt;, psu &lt;dbl&gt;, celphon1 &lt;dbl&gt;,
## #   colgsex1 &lt;dbl&gt;, numadult &lt;dbl&gt;, landsex1 &lt;dbl&gt;, respslct &lt;chr&gt;,
## #   hhadult &lt;dbl&gt;, sexvar &lt;chr&gt;, genhlth &lt;chr&gt;, physhlth &lt;chr&gt;, menthlth &lt;chr&gt;,
## #   poorhlth &lt;chr&gt;, priminsr &lt;chr&gt;, persdoc3 &lt;chr&gt;, medcost1 &lt;chr&gt;,
## #   checkup1 &lt;chr&gt;, exerany2 &lt;chr&gt;, sleptim1 &lt;chr&gt;, lastden4 &lt;chr&gt;,
## #   rmvteth4 &lt;chr&gt;, cvdinfr4 &lt;chr&gt;, cvdcrhd4 &lt;chr&gt;, cvdstrk3 &lt;chr&gt;, …</code></pre>
<pre class="r"><code>county = 
  brfss_22 |&gt;
  filter(ctycode2 != &quot;Data do not meet the criteria for statistical reliability, data quality or confidentiality (data are suppressed)&quot;)

head(county)</code></pre>
<pre><code>## # A tibble: 0 × 343
## # ℹ 343 variables: state &lt;chr&gt;, fmonth &lt;dbl&gt;, idate &lt;chr&gt;, imonth &lt;chr&gt;,
## #   iday &lt;chr&gt;, iyear &lt;dbl&gt;, seqno &lt;dbl&gt;, psu &lt;dbl&gt;, celphon1 &lt;dbl&gt;,
## #   colgsex1 &lt;dbl&gt;, numadult &lt;dbl&gt;, landsex1 &lt;dbl&gt;, respslct &lt;chr&gt;,
## #   hhadult &lt;dbl&gt;, sexvar &lt;chr&gt;, genhlth &lt;chr&gt;, physhlth &lt;chr&gt;, menthlth &lt;chr&gt;,
## #   poorhlth &lt;chr&gt;, priminsr &lt;chr&gt;, persdoc3 &lt;chr&gt;, medcost1 &lt;chr&gt;,
## #   checkup1 &lt;chr&gt;, exerany2 &lt;chr&gt;, sleptim1 &lt;chr&gt;, lastden4 &lt;chr&gt;,
## #   rmvteth4 &lt;chr&gt;, cvdinfr4 &lt;chr&gt;, cvdcrhd4 &lt;chr&gt;, cvdstrk3 &lt;chr&gt;, …</code></pre>
<p>· we try to filter people who live in NYC, but all data are
confidential.</p>
<p><strong>Subset Dataset Cleaning</strong></p>
<pre class="r"><code>cleaned_df = 
  brfss_22 |&gt;
  filter(complete.cases(imprace, educag, incomg1, strsmeal_sa, genhlth))|&gt;
  select(imprace, educag, incomg1, strsmeal_sa, genhlth)</code></pre>
<pre class="r"><code>cleaned_df = 
  cleaned_df |&gt;
  mutate(
    income = case_when(
      incomg1 %in% c(&quot;Less than $15,000&quot;, &quot;$25,000 to &lt; $35,000&quot;, &quot;$35,000 to &lt; $50,000&quot;) ~&quot;&lt;50,000&quot;,
      incomg1 == &quot;$50,000 to &lt; $100,000&quot; ~ &quot;50,000 ~ 100,000&quot;,
      incomg1 %in% c (&quot;$100,000 to &lt; $200,000&quot; , &quot;$200,000 or more&quot;) ~ &quot;&gt;100,000&quot;,
      TRUE ~ NA_character_),
    
    education = case_when(
      educag == &quot;Did not graduate High School&quot; ~ &quot;Less than high school&quot;,
      educag == &quot;Graduated High School&quot; ~ &quot;High school or GED&quot;,
      educag == &quot;Attended College or Technical School&quot; ~ &quot;Some post-high school&quot;,
      educag == &quot;Graduated from College or Technical School&quot; ~ &quot;College graduate&quot;
    ),
    
    food_insecure = case_when(
      strsmeal_sa %in% c(&quot;Rarely&quot;,&quot;Sometimes&quot;,&quot;Usually&quot;, &quot;Always&quot;) ~ 1,
      strsmeal_sa == &quot;Never&quot; ~ 0)
   )|&gt;
  filter(!is.na(income), !is.na(education))|&gt;
  select(-incomg1, -educag, -strsmeal_sa)</code></pre>
<div id="cleaning-step" class="section level3">
<h3>Cleaning Step:</h3>
<p>· First filtering all valid values in the following variables:
imprace, educag, incomg1, strsmeal_sa, genhlth.</p>
<p>· Only selecting these variables that we will use in the following
steps because the original dataset is too large. It is easy to make a
subset dataset.</p>
<p>· After first step filtering, we re-categorize income3, educag, and
strsmeal_sa. The most noticeable change is re-categorizing strsmeal_sa
into a new variable “food-insecure”. We combine rarely, sometimes,
usually, and always into “1” to represent food insecure challenge that
individuals face, and contain never as 0 to represent no food
insecure.</p>
<p>· Last, we remove all missing values from the sub dataset.</p>
<p><strong>Figures Making</strong></p>
<pre class="r"><code>ggplot(data = cleaned_df, aes(x = imprace, fill = imprace))+
  geom_bar() +
  labs(
    title = &quot;Distribution of Race/Ethnicity&quot;,
    x = &quot;Race/Ethnicity&quot;,
    y = &quot;Count&quot;
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) </code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>This bar graph illustrates the distribution of race/ethnicity in the
dataset. The categories include American Indian/Alaskan Native, Asian,
Black, Hispanic, Other Race, and White, all specified as Non-Hispanic
except for the Hispanic group. Among these groups, White, Non-Hispanic
individuals dominate, with the highest count exceeding 6,000. The second
most prevalent group is Hispanic, followed by Black, Non-Hispanic, while
Other Race, Non-Hispanic, and Asian, Non-Hispanic, show significantly
smaller counts. The American Indian/Alaskan Native, Non-Hispanic
category represents the smallest group.</p>
<pre class="r"><code>ggplot(cleaned_df, aes(x = &quot;&quot;, fill = education)) +
  geom_bar(width = 1, stat = &quot;count&quot;) +
  coord_polar(theta = &quot;y&quot;) +
  labs(
    title = &quot;Distribution of Education Levels&quot;,
    fill = &quot;Education Level&quot;
  ) +
  theme_void() +
  theme(legend.position = &quot;right&quot;)</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>This pie chart shows the distribution of education levels within a
dataset. The largest portion of the chart is represented by college
graduates, shown in red, indicating that a significant proportion of
individuals have completed higher education. The second-largest
category, represented in purple, corresponds to individuals with some
post-high school education. High school graduates or those with a GED,
shown in green, form a smaller segment, while the smallest portion of
the chart, in teal, represents individuals with less than a high school
education.</p>
<pre class="r"><code>ggplot(cleaned_df, aes(x = as.factor(food_insecure), fill = as.factor(food_insecure))) +
  geom_bar() +
  scale_fill_manual(values = c(&quot;0&quot; = &quot;lightblue&quot;, &quot;1&quot; = &quot;pink&quot;), labels = c(&quot;Not Food Insecure&quot;, &quot;Food Insecure&quot;)) +
  labs(
    title = &quot;Distribution of Food Insecurity&quot;,
    x = &quot;Food Insecurity&quot;,
    y = &quot;Count&quot;,
    fill = &quot;Status&quot;
  ) +
  theme_minimal()</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This bar graph presents the distribution of food insecurity status
among individuals in the dataset. The largest group, represented in
light blue, comprises individuals who are not food insecure, with a
count exceeding 4,000. The second-largest group, shown in pink,
represents individuals who are food insecure, numbering slightly over
2,000. A very small proportion, represented in gray, corresponds to
missing data (NA) for food insecurity status.</p>
<pre class="r"><code>cleaned_df = 
  cleaned_df |&gt;
  mutate(
    imprace = as.factor(imprace),
    income = as.factor(income),
    education = as.factor(education),
    genhlth = as.factor(genhlth)
  )</code></pre>
</div>
<div id="logistic-regression-models" class="section level2">
<h2><strong>Logistic Regression Models</strong></h2>
<div id="is-income-associated-with-food-insecure"
class="section level3">
<h3>Is income associated with food insecure?</h3>
<pre class="r"><code>logit_income = 
  glm(formula = food_insecure ~ income, data = cleaned_df, family = binomial)</code></pre>
<pre class="r"><code>summary(logit_income)</code></pre>
<pre><code>## 
## Call:
## glm(formula = food_insecure ~ income, family = binomial, data = cleaned_df)
## 
## Coefficients:
##                        Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)             0.15825    0.04214   3.756 0.000173 ***
## income&gt;100,000         -1.79779    0.07055 -25.484  &lt; 2e-16 ***
## income50,000 ~ 100,000 -1.05163    0.06343 -16.580  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8531.8  on 6720  degrees of freedom
## Residual deviance: 7767.5  on 6718  degrees of freedom
##   (14 observations deleted due to missingness)
## AIC: 7773.5
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp_income = exp(cbind(OR=coef(logit_income),confint(logit_income)))

knitr::kable(exp_income)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">OR</th>
<th align="right">2.5 %</th>
<th align="right">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1.1714559</td>
<td align="right">1.0786807</td>
<td align="right">1.2724394</td>
</tr>
<tr class="even">
<td align="left">income&gt;100,000</td>
<td align="right">0.1656645</td>
<td align="right">0.1441346</td>
<td align="right">0.1900589</td>
</tr>
<tr class="odd">
<td align="left">income50,000 ~ 100,000</td>
<td align="right">0.3493678</td>
<td align="right">0.3084065</td>
<td align="right">0.3954708</td>
</tr>
</tbody>
</table>
<p>Intercept: The odds ratio for the intercept (1.171) represents the
baseline odds of being food insecure when income is less than 50,000.
Since the 95% confidence interval (1.079–1.272) does not include 1, it
is statistically significant.</p>
<p>OR: Income &gt; 100,000: The odds ratio (0.166) indicates that
individuals with an income greater than $100,000 have 83.4% lower odds
of being food insecure compared to the income group less than 50,000.
The 95% confidence interval (0.144–0.191) excludes 1, making this result
statistically significant.</p>
<p>Income 50,000–100,000: The odds ratio (0.349) indicates that
individuals with an income between $50,000 and 100,000 have 65.1% lower
odds of being food insecure compared to the income group less than
50,000. The 95% confidence interval (0.308–0.395) excludes 1, so this
result is also statistically significant.</p>
<p>Statistical significance: confidence intervals of OR of both
predictor levels exclude 1, indicating that they are statistically
associated with food insecure.</p>
</div>
<div id="confidence-interval" class="section level3">
<h3>Confidence Interval</h3>
<pre class="r"><code>ci_income = as.data.frame(exp_income)
ci_income = 
  ci_income |&gt; 
  rownames_to_column(&quot;Variable&quot;) |&gt; 
  filter(Variable != &quot;(Intercept)&quot;) </code></pre>
<pre class="r"><code>ggplot(ci_income, aes(y = Variable, x = OR, xmin = `2.5 %`, xmax = `97.5 %`)) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(
    title = &quot;Odds Ratios with 95% Confidence Intervals&quot;,
    x = &quot;Odds Ratio (OR)&quot;,
    y = &quot;Income Category&quot;
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 12))</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="is-race-associated-with-food-insecure" class="section level3">
<h3>Is race associated with food insecure?</h3>
<pre class="r"><code>logit_race = 
  glm(food_insecure ~ imprace, data = cleaned_df, family = binomial)</code></pre>
<pre class="r"><code>summary(logit_race)</code></pre>
<pre><code>## 
## Call:
## glm(formula = food_insecure ~ imprace, family = binomial, data = cleaned_df)
## 
## Coefficients:
##                                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                       0.4700     0.3291   1.428  0.15330    
## impraceAsian, Non-Hispanic       -1.1448     0.3494  -3.277  0.00105 ** 
## impraceBlack, Non-Hispanic       -0.6395     0.3388  -1.888  0.05907 .  
## impraceHispanic                  -0.1845     0.3368  -0.548  0.58379    
## impraceOther race, Non-Hispanic  -0.8530     0.3817  -2.235  0.02544 *  
## impraceWhite, Non-Hispanic       -1.4665     0.3307  -4.434 9.25e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8531.8  on 6720  degrees of freedom
## Residual deviance: 8193.8  on 6715  degrees of freedom
##   (14 observations deleted due to missingness)
## AIC: 8205.8
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp_race = exp(cbind(OR=coef(logit_race),confint(logit_race)))

knitr::kable(exp_race)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">OR</th>
<th align="right">2.5 %</th>
<th align="right">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1.6000000</td>
<td align="right">0.8482021</td>
<td align="right">3.1174422</td>
</tr>
<tr class="even">
<td align="left">impraceAsian, Non-Hispanic</td>
<td align="right">0.3182870</td>
<td align="right">0.1573729</td>
<td align="right">0.6250436</td>
</tr>
<tr class="odd">
<td align="left">impraceBlack, Non-Hispanic</td>
<td align="right">0.5275735</td>
<td align="right">0.2660540</td>
<td align="right">1.0145649</td>
</tr>
<tr class="even">
<td align="left">impraceHispanic</td>
<td align="right">0.8315217</td>
<td align="right">0.4208835</td>
<td align="right">1.5927584</td>
</tr>
<tr class="odd">
<td align="left">impraceOther race, Non-Hispanic</td>
<td align="right">0.4261364</td>
<td align="right">0.1982346</td>
<td align="right">0.8920934</td>
</tr>
<tr class="even">
<td align="left">impraceWhite, Non-Hispanic</td>
<td align="right">0.2307309</td>
<td align="right">0.1180762</td>
<td align="right">0.4366356</td>
</tr>
</tbody>
</table>
<p>Intercept: The odds ratio for the intercept (1.6) represents the odds
of being food insecure for the reference group (American Indian/Alaskan
Native). Since the 95% confidence interval (0.848–3.117) includes 1,
this result is not statistically significant.</p>
<p>OR: Asian, Non-Hispanic: The odds ratio (0.318) indicates that Asian,
Non-Hispanic individuals have 68.2% lower odds of being food insecure
compared to American Indians. The 95% confidence interval (0.157–0.625)
excludes 1, so this result is statistically significant.</p>
<p>Black, Non-Hispanic: The odds ratio (0.528) suggests that Black,
Non-Hispanic individuals have 47.2% lower odds of being food insecure
compared to American Indians. However, the 95% confidence interval
(0.266–1.015) includes 1, making this result not statistically
significant.</p>
<p>Hispanic: The odds ratio (0.832) implies that Hispanic individuals
have 16.8% lower odds of being food insecure compared to American
Indians. Since the 95% confidence interval (0.421–1.593) includes 1,
this result is not statistically significant.</p>
<p>Other Race, Non-Hispanic: The odds ratio (0.426) indicates that
individuals of Other Race, Non-Hispanic have 57.4% lower odds of being
food insecure compared to American Indians. The 95% confidence interval
(0.198–0.892) excludes 1, so this result is statistically
significant.</p>
<p>White, Non-Hispanic: The odds ratio (0.230) suggests that White,
Non-Hispanic individuals have 77% lower odds of being food insecure
compared to American Indians. The 95% confidence interval (0.118–0.437)
excludes 1, so this result is statistically significant.</p>
<p>Statistical significance: confidence intervals of OR of all predictor
levels except Black and Hispanic exclude 1, indicating that these
predictor levels are statistically significant.</p>
</div>
<div id="confidence-interval-1" class="section level3">
<h3>Confidence Interval</h3>
<pre class="r"><code>ci_race = as.data.frame(exp_race)
ci_race = 
  ci_race |&gt; 
  rownames_to_column(&quot;Variable&quot;) |&gt; 
  filter(Variable != &quot;(Intercept)&quot;) </code></pre>
<pre class="r"><code>ggplot(ci_race, aes(y = Variable, x = OR, xmin = `2.5 %`, xmax = `97.5 %`)) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(
    title = &quot;Odds Ratios with 95% Confidence Intervals&quot;,
    x = &quot;Odds Ratio (OR)&quot;,
    y = &quot;Income Category&quot;
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 12))</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="is-education-associated-with-food-insecure"
class="section level3">
<h3>Is education associated with food insecure?</h3>
<pre class="r"><code>logit_edu = 
  glm(food_insecure ~ education, data = cleaned_df, family = binomial)</code></pre>
<pre class="r"><code>summary(logit_edu)</code></pre>
<pre><code>## 
## Call:
## glm(formula = food_insecure ~ education, family = binomial, data = cleaned_df)
## 
## Coefficients:
##                                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                    -1.17472    0.03990  -29.44   &lt;2e-16 ***
## educationHigh school or GED     0.89353    0.06799   13.14   &lt;2e-16 ***
## educationLess than high school  1.65655    0.12013   13.79   &lt;2e-16 ***
## educationSome post-high school  0.75108    0.06534   11.49   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8531.8  on 6720  degrees of freedom
## Residual deviance: 8181.7  on 6717  degrees of freedom
##   (14 observations deleted due to missingness)
## AIC: 8189.7
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp_edu = exp(cbind(OR=coef(logit_edu),confint(logit_edu)))

knitr::kable(exp_edu)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">OR</th>
<th align="right">2.5 %</th>
<th align="right">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.3089064</td>
<td align="right">0.2855101</td>
<td align="right">0.3338597</td>
</tr>
<tr class="even">
<td align="left">educationHigh school or GED</td>
<td align="right">2.4437471</td>
<td align="right">2.1388216</td>
<td align="right">2.7921872</td>
</tr>
<tr class="odd">
<td align="left">educationLess than high school</td>
<td align="right">5.2412235</td>
<td align="right">4.1483184</td>
<td align="right">6.6458564</td>
</tr>
<tr class="even">
<td align="left">educationSome post-high school</td>
<td align="right">2.1192858</td>
<td align="right">1.8644532</td>
<td align="right">2.4088344</td>
</tr>
</tbody>
</table>
<p>Intercept: The odds ratio for the intercept (0.309) represents the
odds of being food insecure for individuals in the reference group
(College graduates).</p>
<p>OR: High School or GED: The odds ratio (2.444) indicates that
individuals with a high school diploma or GED have 144.4% higher odds of
being food insecure compared to college graduates.</p>
<p>Less than High School: The odds ratio (5.241) suggests that
individuals with less than a high school education have 424.1% higher
odds of being food insecure compared to college graduates.</p>
<p>Some Post-High School: The odds ratio (2.119) indicates that
individuals with some post-high school education have 111.9% higher odds
of being food insecure compared to college graduates.</p>
<p>Statistical significance: confidence intervals of OR of all three
predictor levels exclude 1, making these results statistically
significant.</p>
</div>
<div id="confidence-interval-2" class="section level3">
<h3>Confidence Interval</h3>
<pre class="r"><code>ci_edu = as.data.frame(exp_edu)
ci_edu = 
  ci_edu |&gt; 
  rownames_to_column(&quot;Variable&quot;) |&gt; 
  filter(Variable != &quot;(Intercept)&quot;) </code></pre>
<pre class="r"><code>ggplot(ci_edu, aes(y = Variable, x = OR, xmin = `2.5 %`, xmax = `97.5 %`)) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(
    title = &quot;Odds Ratios with 95% Confidence Intervals&quot;,
    x = &quot;Odds Ratio (OR)&quot;,
    y = &quot;Income Category&quot;
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 12))</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
<div id="are-race-education-and-income-associated-with-food-insecure"
class="section level3">
<h3>Are race, education, and income associated with food insecure?</h3>
<pre class="r"><code>logit_all = 
  glm(food_insecure ~ education + income + imprace, data = cleaned_df, family = binomial)</code></pre>
<pre class="r"><code>summary(logit_all)</code></pre>
<pre><code>## 
## Call:
## glm(formula = food_insecure ~ education + income + imprace, family = binomial, 
##     data = cleaned_df)
## 
## Coefficients:
##                                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                      0.53189    0.35172   1.512 0.130472    
## educationHigh school or GED      0.33709    0.07560   4.459 8.25e-06 ***
## educationLess than high school   0.51381    0.13410   3.832 0.000127 ***
## educationSome post-high school   0.39938    0.07067   5.652 1.59e-08 ***
## income&gt;100,000                  -1.47996    0.07716 -19.181  &lt; 2e-16 ***
## income50,000 ~ 100,000          -0.82727    0.06720 -12.310  &lt; 2e-16 ***
## impraceAsian, Non-Hispanic      -0.61142    0.37016  -1.652 0.098582 .  
## impraceBlack, Non-Hispanic      -0.35711    0.35843  -0.996 0.319098    
## impraceHispanic                 -0.02493    0.35628  -0.070 0.944225    
## impraceOther race, Non-Hispanic -0.50427    0.40436  -1.247 0.212367    
## impraceWhite, Non-Hispanic      -0.95198    0.35036  -2.717 0.006584 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8531.8  on 6720  degrees of freedom
## Residual deviance: 7556.1  on 6710  degrees of freedom
##   (14 observations deleted due to missingness)
## AIC: 7578.1
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp_all = exp(cbind(OR=coef(logit_all),confint(logit_all)))

knitr::kable(exp_all)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">OR</th>
<th align="right">2.5 %</th>
<th align="right">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1.7021419</td>
<td align="right">0.8647852</td>
<td align="right">3.4657343</td>
</tr>
<tr class="even">
<td align="left">educationHigh school or GED</td>
<td align="right">1.4008627</td>
<td align="right">1.2075946</td>
<td align="right">1.6242264</td>
</tr>
<tr class="odd">
<td align="left">educationLess than high school</td>
<td align="right">1.6716442</td>
<td align="right">1.2863633</td>
<td align="right">2.1766833</td>
</tr>
<tr class="even">
<td align="left">educationSome post-high school</td>
<td align="right">1.4909056</td>
<td align="right">1.2977759</td>
<td align="right">1.7120630</td>
</tr>
<tr class="odd">
<td align="left">income&gt;100,000</td>
<td align="right">0.2276472</td>
<td align="right">0.1955464</td>
<td align="right">0.2646223</td>
</tr>
<tr class="even">
<td align="left">income50,000 ~ 100,000</td>
<td align="right">0.4372422</td>
<td align="right">0.3831784</td>
<td align="right">0.4986752</td>
</tr>
<tr class="odd">
<td align="left">impraceAsian, Non-Hispanic</td>
<td align="right">0.5425790</td>
<td align="right">0.2575868</td>
<td align="right">1.1083291</td>
</tr>
<tr class="even">
<td align="left">impraceBlack, Non-Hispanic</td>
<td align="right">0.6996939</td>
<td align="right">0.3394655</td>
<td align="right">1.3960468</td>
</tr>
<tr class="odd">
<td align="left">impraceHispanic</td>
<td align="right">0.9753822</td>
<td align="right">0.4750575</td>
<td align="right">1.9375440</td>
</tr>
<tr class="even">
<td align="left">impraceOther race, Non-Hispanic</td>
<td align="right">0.6039454</td>
<td align="right">0.2687842</td>
<td align="right">1.3203476</td>
</tr>
<tr class="odd">
<td align="left">impraceWhite, Non-Hispanic</td>
<td align="right">0.3859749</td>
<td align="right">0.1900830</td>
<td align="right">0.7577675</td>
</tr>
</tbody>
</table>
<p>Statistical Significant Predictors:</p>
<p>Education: Individuals with a high school diploma or GED have 40.1%
higher odds of being food insecure compared to college graduates.
Individuals with less than a high school education have 67.1% higher
odds of being food insecure compared to college graduates. Individuals
with some post-high school education have 49.1% higher odds of being
food insecure compared to college graduates.</p>
<p>Income: Individuals earning over 100,000 have 77.2% lower odds of
being food insecure compared to those earning ≤ $50,000. Individuals
earning between $50,000 and $100,000 have 56.3% lower odds of being food
insecure compared to those earning ≤ $50,000.</p>
<p>Race/Ethnicity: White, Non-Hispanic individuals have 61.4% lower odds
of being food insecure compared to American Indians.</p>
<p>Summary: Education and income levels show significant associations
with food insecurity, with lower education and income levels increasing
odds of food insecurity.Among racial/ethnic groups, only White,
Non-Hispanic individuals show significantly lower odds of food
insecurity compared to American Indians.</p>
</div>
<div id="confidence-interval-3" class="section level3">
<h3>Confidence Interval</h3>
<pre class="r"><code>ci_all = as.data.frame(exp_all)
ci_all = 
  ci_all |&gt; 
  rownames_to_column(&quot;Variable&quot;) |&gt; 
  filter(Variable != &quot;(Intercept)&quot;) </code></pre>
<pre class="r"><code>ggplot(ci_all, aes(y = Variable, x = OR, xmin = `2.5 %`, xmax = `97.5 %`)) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(
    title = &quot;Odds Ratios with 95% Confidence Intervals&quot;,
    x = &quot;Odds Ratio (OR)&quot;,
    y = &quot;Income Category&quot;
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 12))</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
<div id="is-food-insecure-associated-with-general-health"
class="section level3">
<h3>Is food insecure associated with general health?</h3>
<pre class="r"><code>mlogit_health = 
  vglm(genhlth ~ food_insecure, data = cleaned_df, family = multinomial(refLevel = &quot;Fair&quot;))</code></pre>
<pre class="r"><code>summary(mlogit_health)</code></pre>
<pre><code>## Call:
## vglm(formula = genhlth ~ food_insecure, family = multinomial(refLevel = &quot;Fair&quot;), 
##     data = cleaned_df)
## 
## Coefficients: 
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept):1   -4.59512    0.50252  -9.144  &lt; 2e-16 ***
## (Intercept):2    0.85806    0.05997  14.309  &lt; 2e-16 ***
## (Intercept):3    1.17943    0.05746  20.526  &lt; 2e-16 ***
## (Intercept):4   -1.62471    0.12388 -13.115  &lt; 2e-16 ***
## (Intercept):5   -4.37198    0.45003  -9.715  &lt; 2e-16 ***
## (Intercept):6    1.51023    0.05552  27.199  &lt; 2e-16 ***
## food_insecure:1 -1.31568    1.12033  -1.174  0.24025    
## food_insecure:2 -1.12341    0.09919 -11.325  &lt; 2e-16 ***
## food_insecure:3 -0.40687    0.08522  -4.774 1.81e-06 ***
## food_insecure:4  0.46750    0.16333   2.862  0.00421 ** 
## food_insecure:5 -1.53882    1.09779  -1.402  0.16099    
## food_insecure:6 -0.93792    0.08557 -10.961  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Number of linear predictors:  6 
## 
## Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3]), 
## log(mu[,4]/mu[,3]), log(mu[,5]/mu[,3]), log(mu[,6]/mu[,3]), log(mu[,7]/mu[,3])
## 
## Residual deviance: 18580.58 on 40314 degrees of freedom
## 
## Log-likelihood: -9290.288 on 40314 degrees of freedom
## 
## Number of Fisher scoring iterations: 9 
## 
## Warning: Hauck-Donner effect detected in the following estimate(s):
## &#39;(Intercept):1&#39;, &#39;(Intercept):5&#39;
## 
## 
## Reference group is level  3  of the response</code></pre>
<pre class="r"><code>exp_health = exp(cbind(OR=coef(mlogit_health),confint(mlogit_health)))

knitr::kable(exp_health)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">OR</th>
<th align="right">2.5 %</th>
<th align="right">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept):1</td>
<td align="right">0.0101010</td>
<td align="right">0.0037724</td>
<td align="right">0.0270464</td>
</tr>
<tr class="even">
<td align="left">(Intercept):2</td>
<td align="right">2.3585859</td>
<td align="right">2.0970490</td>
<td align="right">2.6527407</td>
</tr>
<tr class="odd">
<td align="left">(Intercept):3</td>
<td align="right">3.2525253</td>
<td align="right">2.9061006</td>
<td align="right">3.6402458</td>
</tr>
<tr class="even">
<td align="left">(Intercept):4</td>
<td align="right">0.1969697</td>
<td align="right">0.1545092</td>
<td align="right">0.2510988</td>
</tr>
<tr class="odd">
<td align="left">(Intercept):5</td>
<td align="right">0.0126263</td>
<td align="right">0.0052265</td>
<td align="right">0.0305028</td>
</tr>
<tr class="even">
<td align="left">(Intercept):6</td>
<td align="right">4.5277778</td>
<td align="right">4.0609020</td>
<td align="right">5.0483295</td>
</tr>
<tr class="odd">
<td align="left">food_insecure:1</td>
<td align="right">0.2682927</td>
<td align="right">0.0298527</td>
<td align="right">2.4112053</td>
</tr>
<tr class="even">
<td align="left">food_insecure:2</td>
<td align="right">0.3251684</td>
<td align="right">0.2677158</td>
<td align="right">0.3949506</td>
</tr>
<tr class="odd">
<td align="left">food_insecure:3</td>
<td align="right">0.6657325</td>
<td align="right">0.5633216</td>
<td align="right">0.7867615</td>
</tr>
<tr class="even">
<td align="left">food_insecure:4</td>
<td align="right">1.5959975</td>
<td align="right">1.1587934</td>
<td align="right">2.1981555</td>
</tr>
<tr class="odd">
<td align="left">food_insecure:5</td>
<td align="right">0.2146341</td>
<td align="right">0.0249609</td>
<td align="right">1.8455962</td>
</tr>
<tr class="even">
<td align="left">food_insecure:6</td>
<td align="right">0.3914410</td>
<td align="right">0.3310014</td>
<td align="right">0.4629166</td>
</tr>
</tbody>
</table>
<p>OR: Individuals who are food insecure have 73.2% lower odds of
reporting “Poor” health compared to “Fair” health when compared to
non-food insecure individuals. Food-insecure individuals have 67.4%
lower odds of reporting “Good” health compared to “Fair” health than
non-food insecure individuals. Food-insecure individuals have 33.4%
lower odds of reporting “Very Good” health compared to “Fair” health
than non-food insecure individuals. Food-insecure individuals have 59.6%
higher odds of reporting “Excellent” health compared to “Fair” health
than non-food insecure individuals.</p>
<p>Statistical significance: confidence intervals of OR of “Good”, “Very
Good”, and “Excellent” health group exclude 1, indicating that these
predictor levels are statistically significant.</p>
<p>This analysis emphasizes that food insecurity significantly affects
perceived health levels. The result that individuals with food insecure
have a higher odds ratio to report “Excellent” health compared to “Fair”
health is very weird. The result may be influenced by individuals’
perceptions, cultural norms, and personal experiences. Furthermore,
individuals who recently are experiencing food insecurity might still
maintain good physical health but are at the early stages of economic or
food-related struggles, leading them to perceive their health as
excellent. Therefore, the limitation of this regression is excluding
confouders.</p>
</div>
<div id="confidence-interval-4" class="section level3">
<h3>Confidence Interval</h3>
<pre class="r"><code>coefs &lt;- coef(summary(mlogit_health))
odds_ratios &lt;- exp(coefs[, &quot;Estimate&quot;]) # Convert coefficients to odds ratios
lower_ci &lt;- exp(coefs[, &quot;Estimate&quot;] - 1.96 * coefs[, &quot;Std. Error&quot;]) # Lower 95% CI
upper_ci &lt;- exp(coefs[, &quot;Estimate&quot;] + 1.96 * coefs[, &quot;Std. Error&quot;]) # Upper 95% CI

# Combine into a tidy data frame
ci_data &lt;- data.frame(
  Variable = rownames(coefs),
  OR = odds_ratios,
  Lower = lower_ci,
  Upper = upper_ci
) |&gt;
  filter(!grepl(&quot;(Intercept)&quot;, Variable)) |&gt; # Exclude intercepts
  separate(Variable, into = c(&quot;Outcome&quot;, &quot;Predictor&quot;), sep = &quot;: &quot;, fill = &quot;right&quot;)</code></pre>
<pre class="r"><code>ggplot(ci_data, aes(y = Outcome, x = OR, xmin = Lower, xmax = Upper, color = Predictor)) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(
    title = &quot;Odds Ratios with 95% Confidence Intervals&quot;,
    x = &quot;Odds Ratio (OR)&quot;,
    y = &quot;Outcome (General Health)&quot;,
    color = &quot;Predictor&quot;
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 12))</code></pre>
<p><img src="data_analysis_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
