---
title: "Data Analysis"
output: 
  html_document:
    toc: false
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(haven)
library(VGAM)
```


Visit [report](report.html) for detailed steps on how the data is cleaned.
```{r}
brfss_22 = read_csv("NYSDOH_BRFSS_Survey_Data_2022.csv")|>
  janitor::clean_names()

cleaned_df = 
  brfss_22 |>
  filter(complete.cases(imprace, educag, incomg1, strsmeal_sa, genhlth, diabete4, ment14d, phys14d))|>
  select(imprace, educag, incomg1, strsmeal_sa, genhlth, diabete4, ment14d, phys14d)

cleaned_df = 
  cleaned_df |>
  mutate(
    income = case_when(
      incomg1 %in% c("Less than $15,000", "$25,000 to < $35,000", "$35,000 to < $50,000") ~"<50,000",
      incomg1 == "$50,000 to < $100,000" ~ "50,000 ~ 100,000",
      incomg1 %in% c ("$100,000 to < $200,000" , "$200,000 or more") ~ ">100,000",
      TRUE ~ NA_character_),
    
    education = case_when(
      educag == "Did not graduate High School" ~ "Less than high school",
      educag == "Graduated High School" ~ "High school or GED",
      educag == "Attended College or Technical School" ~ "Some post-high school",
      educag == "Graduated from College or Technical School" ~ "College graduate"
    ),
    
    food_insecure = case_when(
      strsmeal_sa %in% c("Rarely","Sometimes","Usually", "Always") ~ 1,
      strsmeal_sa == "Never" ~ 0),
    
    health = case_when(
      genhlth %in% c("Good", "Very good", "Excellent") ~ 1,
      genhlth %in% c("Fair", "Poor") ~ 0),
    
    physical_health = case_when(
      phys14d %in% c("Zero days when physical health not good") ~ 0,
      phys14d %in% c("1-13 days when physical health not good", "14+ days when physical health not good") ~ 1),
    
    mental_health = case_when(
      ment14d %in% c("Zero days when mental health not good") ~ 0,
      ment14d %in% c("1-13 days when mental health not good", "14+ days when physical health not good") ~ 1)
    
   )|>
  filter(!is.na(income), !is.na(education), !is.na(physical_health), !is.na(mental_health))|>
  select(-incomg1, -educag, -strsmeal_sa, -genhlth, -phys14d, -ment14d)

```


### Is food insecure associated with general health?
```{r}
logit_health = 
  glm(health ~ food_insecure, data = cleaned_df, family = binomial)

exp_health = exp(cbind(OR=coef(logit_health),confint(logit_health)))

knitr::kable(exp_health)
```



### Confidence Interval
```{r}
coefs <- coef(summary(logit_health))
odds_ratios <- exp(coefs[, "Estimate"]) # Convert coefficients to odds ratios
lower_ci <- exp(coefs[, "Estimate"] - 1.96 * coefs[, "Std. Error"]) # Lower 95% CI
upper_ci <- exp(coefs[, "Estimate"] + 1.96 * coefs[, "Std. Error"]) # Upper 95% CI

# Combine into a tidy data frame
ci_data <- data.frame(
  Variable = rownames(coefs),
  OR = odds_ratios,
  Lower = lower_ci,
  Upper = upper_ci
) |>
  filter(!grepl("(Intercept)", Variable)) |> # Exclude intercepts
  separate(Variable, into = c("Outcome", "Predictor"), sep = ": ", fill = "right")
```


```{r}
ggplot(ci_data, aes(y = Outcome, x = OR, xmin = Lower, xmax = Upper, color = Predictor)) +
  geom_pointrange() +
  geom_vline(xintercept = 1, linetype = "dashed", color = "red") +
  labs(
    title = "Odds Ratios with 95% Confidence Intervals",
    x = "Odds Ratio (OR)",
    y = "Outcome (General Health)",
    color = "Predictor"
  ) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 12))
```



